version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "automerge"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      patch-and-minor:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      patch-and-minor:
        update-types:
          - "minor"
          - "patch"
