name: Nightly Tests

on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  nightly:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
          pip install -e .

      - name: Run tests with coverage
        run: |
          pytest --cov=src --cov-report=term --cov-fail-under=80 -v

      - name: Notify if failed
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: alerts
          SLACK_TITLE: Nightly Tests Failed
          SLACK_MESSAGE: The nightly tests failed. Please check the logs.
          SLACK_COLOR: danger
